[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "xatu"
authors = [{name = "Alejandro José Uría-Álvarez"}]
dynamic = ["version", "description"]

